---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/jonathonp3/orange-os
name: Orange-OS
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
    - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # Codecs Encoding
      - ffmpeg
      - ffmpeg-libs
      - ffmpegthumbnailer
      - yt-dlp
      
      # Containers
    # - distrobox
      
      # Editors
      - pluma
      - vim
  
      # Virtualisation
      - qemu
      - libvirt
      - virt-manager
      - virt-install
     
      # 
      - flatpak-spaw
    # - fuse
      - grub2-tools-extra
      - gparted
      - lshw
      - micro
      - net-tools
      - python
      - python3-pip # gext
      - rsync
      - smartmontools
      - syncthing
      - starship
      - tailscale
      - traceroute
      - zstd
      - wireguard-tools

     
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        
        - com.github.tchx84.Flatseal
        - com.google.Chrome
        - com.spotify.Client
        - io.bassi.Amberol
        - io.github.ungoogled_software.ungoogled_chromium
        - it.mijorus.gearlever
      # - org.clementine_player.Clementine
        - org.kde.kdenlive
        - org.keepassxc.KeePassXC
        - org.freac.freac
        - org.gimp.GIMP
        - org.gnome.Evolution
        - org.gnome.gedit
        - org.gnome.gThumb
        - org.gnome.Rhythmbox3
        - org.gnome.SimpleScan
        - org.kde.kid3
        - org.signal.Signal
      # - org.libreoffice.LibreOffice
        - org.telegram.desktop
        - org.videolan.VLC

      remove:
      # - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages
     - type: script
    scripts:

  - type: systemd
    system:
      enabled:
     #  - fabric.service  
    user:
      enabled:
     # - syncthing.service
     
  - type: fonts
    fonts:
  
      google-fonts:
       - google-noto-sans-balinese-fonts
       - google-noto-sans-cjk-fonts
       - google-noto-sans-javanese-fonts
       - google-noto-sans-sundanese-fonts
       - google-roboto-fonts

  - type: gnome-extensions
    install: 
     # - https://extensions.gnome.org/extension/3/bottom-panel/
     # - https://extensions.gnome.org/extension/2/move-clock/
       - https://extensions.gnome.org/extension/1462/panel-date-format/
       - https://extensions.gnome.org/extension/4/panel-favorites/
     # - https://extensions.gnome.org/extension/6843/tailscale-connect/
       - https://extensions.gnome.org/extension/602/window-list/
    
       
    

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

