---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Orange-OS
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      
      - qemu
      - libvirt
      - virt-manager
      - virt-install

      - gparted
      - lshw
      - net-tools
      - pluma
      - rsync
      - smartmontools
      - syncthing
      - traceroute
      - vim
      - zstd
      - yt-dlp
      - wireguard-tools
      
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.github.tchx84.Flatseal
        - com.google.Chrome
        - com.spotify.Client
        - io.bassi.Amberol
        - it.mijorus.gearlever
        - org.kde.kdenlive
        - org.freac.freac
        - org.gimp.GIMP
        - org.gnome.Evolution
        - org.gnome.gedit
        - org.gnome.gThumb
        - org.gnome.gedit
        - org.gnome.Rhythmbox3
        - org.gnome.SimpleScan
        - org.kde.kid3
        - org.signal.Signal
        - org.telegram.desktop
        - org.videolan.VLC
        
    user: {} # Also add Flathub user repo, but no user packages
  
  - type: bling
      install:
        - negativo17


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
